services:
  server:
    image: blog-back
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/db
      - SECRET=salaisuus
    container_name: todo-back
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./backend/mongo_data:/data/db
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - server
      - app
  app:
    image: blog-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blog-front
    depends_on:
      - server